#!/bin/bash
#change brightness 0-100
PERCENT=$1
OUTPUT=$(cat /sys/class/backlight/gmux_backlight/max_brightness);
PROP=$(($OUTPUT*$1/100));
echo $PROP > /sys/class/backlight/gmux_backlight/brightness;
echo $PROP;
